[profile.default]
remappings = [
  "hardhat/=node_modules/hardhat/",
  "forge-std/=lib/forge-std/src/",
  "ds-test/=lib/ds-test/src/",
  "solmate/=lib/solmate/src/",
  "@openzeppelin/=node_modules/@openzeppelin/",
  "@nilfoundation/=node_modules/@nilfoundation/",
] 
script = "script" 
sender = '0x7580E71C10e5023a46DD11F21116471dcd60C400' # the address of `msg.sender` in tests
solc = "0.8.28" 
solc_version = '0.8.28' # override for the solc version (setting this ignores `auto_detect_solc`)
src = "contracts" 
test = "/build/source/rollup-bridge-contracts/test" 
tx_origin = '0x7580E71C10e5023a46DD11F21116471dcd60C400' # the address of `tx.origin` in tests
verbosity = 2 # the verbosity of tests
via_ir = true 

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# Test the optimized contracts without re-compiling them
[profile.test-optimized]
src = "tests"

# Speed up compilation and tests during development
[profile.lite]
auto_detect_solc = false 
block_base_fee_per_gas = 0 # the base fee (in wei) in tests
block_coinbase = '0x0000000000000000000000000000000000000000' # the address of `block.coinbase` in tests
block_difficulty = 0 # the value of `block.difficulty` in tests
block_number = 0 # the block number we are at in tests
block_timestamp = 0 # the value of `block.timestamp` in tests
bytecode_hash = "none" 
evm_version = "cancun" 
ffi = false # whether to enable ffi or not
fs_permissions = [
  {access = "read", path = "./"},
  {access = "read", path = "package.json"},
  {access = "read-write", path = "./benchmark/results"},
  {access = "read", path = "./out-optimized"},
  {access = "read-write", path = "./scripts/"},
  {access = "read-write", path = "./deploy/"},
] 
fuzz_runs = 256 # the number of fuzz runs for tests
gas_limit = 9223372036854775807 # the gas limit in tests
gas_price = 0 # the gas price (in wei) in tests
initial_balance = '0xffffffffffffffffffffffff' # the initial balance of the test contract
libs = ["lib"] 
optimizer = true 
optimizer_runs = 1000 
out = "out"
